# Generated by Django 4.2.5 on 2023-10-06 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flatmate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('kind', models.CharField(default=None, max_length=100, null=True)),
                ('roomsize', models.CharField(default=None, max_length=100, null=True)),
                ('rent', models.CharField(default=None, max_length=100, null=True)),
                ('available', models.CharField(default=None, max_length=100, null=True)),
                ('suitable', models.CharField(default=None, max_length=100, null=True)),
                ('flat', models.CharField(default=None, max_length=100, null=True)),
                ('provided', models.CharField(default=None, max_length=100, null=True)),
                ('roomIncluded', models.CharField(default=None, max_length=100, null=True)),
                ('photo', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('room_image_field', models.ImageField(default=None, null=True, upload_to='roomImage/')),
                ('user_image_field', models.ImageField(default=None, null=True, upload_to='userImage/')),
                ('room_file_path', models.CharField(default=None, max_length=255, null=True)),
                ('user_file_path', models.CharField(default=None, max_length=255, null=True)),
                ('auth', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('getStart', models.CharField(default=None, max_length=100, null=True)),
                ('describeItem', models.CharField(default=None, max_length=100, null=True)),
                ('country', models.CharField(default=None, max_length=100, null=True)),
                ('living', models.CharField(default=None, max_length=100, null=True)),
                ('address', models.CharField(default=None, max_length=100, null=True)),
                ('preparePay', models.CharField(default=None, max_length=100, null=True)),
                ('kind', models.CharField(default=None, max_length=100, null=True)),
                ('room_size', models.CharField(default=None, max_length=100, null=True)),
                ('move_date', models.CharField(default=None, max_length=100, null=True)),
                ('coming', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
                ('auth', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('preparePay', models.CharField(default=None, max_length=100, null=True)),
                ('kind', models.CharField(default=None, max_length=100, null=True)),
                ('room_size', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
