# Generated by Django 4.2.5 on 2023-10-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_flatmate_imagemodel_room_savedrooms_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedrooms',
            old_name='preparePay',
            new_name='cost',
        ),
    ]
