# Generated by Django 4.2.5 on 2023-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_room_preparepay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrooms',
            name='cost',
            field=models.IntegerField(default=None, max_length=100, null=True),
        ),
    ]
